Homework 8 Hanna Dziahel
vasilikliapets/QA03_onl pull request #102
Opened 2021-10-28 19:49 UTC by hanna-dziahel

2021-10-30 13:38 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_5.py
> +        new_tup = tuples[::-1]
функция принимает все свои не именованные аргументы в порядке,
# обратном тому, в котором их передали
тут тебе надо вызывать функцию свою изначальную с аргументами в обратном порядке, счас ты ее не вызываешь, а просто возвращаешь аргументы

2021-10-30 13:44 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_4.py
> +            string = func.__name__ + "\n" + str(list(result))
не понимаю зачем теюе эта проверка и возвращать значение твоей функции с ее именем?
счас если есть параметр в функции, то вывод
Имя функции:  honey_
['c', 'u', 't', 'e', ' ', 'k', 'i', 't', 't', 'e', 'n']
а по условию надо только имя функции

2021-10-30 13:44 UTC, vasilikliapets requested changes
нужны небольшие правки

2021-11-02 11:12 UTC, hanna-dziahel commented on Hanna_Dziahel/Lesson8/task8_4.py
> +            string = func.__name__ + "\n" + str(list(result))
добавила эту проверку, так как появлялись проблемы в задании 8.7, когда я использовала этот декоратор

2021-11-02 11:12 UTC, hanna-dziahel commented on Hanna_Dziahel/Lesson8/task8_4.py
> +            string = func.__name__ + "\n" + str(list(result))
убрать эту проверку?

2021-11-03 12:12 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_4.py
> +            string = func.__name__ + "\n" + str(list(result))
не, тогда не надо

2021-11-03 12:25 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_1.py
> +# Напишите декоратор, который печатает перед и после вызова функции
еще у тебя конфликт

Conflicting files
.gitignore

2021-11-03 20:20 UTC, hanna-dziahel commented on Hanna_Dziahel/Lesson8/task8_5.py
> +        new_tup = tuples[::-1]
добавила коммит

2021-11-07 09:47 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_1_extra.py
> +def caching(func):
caching должен принимать timeout

2021-11-07 09:49 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_1_extra.py
> +    def clear_cache(key: int, timeout: int):
по сути эта функция лишняя, эти действия можно сделать во wrapper
я там в телеграмм скинул пример,

2021-11-07 09:51 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_1_extra.py
> +        thread = threading.Thread(target=clear_cache, args=(key, 3, ))
молодец что ты знаешь Thread)))
но он тут явно лишний, можно просто обойтить обычным вычислением времени, и если меньше таймаута - то ничего не делать, а если больше, то вычислять результат функции

2021-11-07 09:54 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson8/task8_7.py
> +        yield a
генератор это хорошо!

2021-11-07 09:54 UTC, vasilikliapets requested changes
нужны правки

2021-11-13 10:45 UTC, vasilikliapets approved these changes
ок

2021-11-13 10:45 UTC, merged