Homework8/andry hlebko
vasilikliapets/QA03_onl pull request #116
Opened 2021-11-03 13:16 UTC by andrgit

2021-11-07 10:48 UTC, vasilikliapets commented on Andrei_hlebko/Lesson8/H8_decorators.py
> +        func(x) + 1
это строчка лишняя

2021-11-07 10:50 UTC, vasilikliapets commented on Andrei_hlebko/Lesson8/H8_decorators.py
> +        return (list[::-1])
тут надо подавать эти параметры в функцию
result = func(args[::-1])
 и переменную list лучше не называть - это зарезервированное слово

2021-11-07 10:56 UTC, vasilikliapets requested changes
нужны небольшие правки

2021-11-09 10:20 UTC, andrgit commented on Andrei_hlebko/Lesson8/H8_decorators.py
> +        return (list[::-1])
fixed bugs

2021-11-09 10:20 UTC, andrgit reviewed
fix bugs

2021-11-09 10:20 UTC, andrgit commented
fixed

2021-11-09 10:30 UTC, vasilikliapets approved these changes
ок

2021-11-09 10:30 UTC, merged