Homework8_Extra
vasilikliapets/QA03_onl pull request #118
Opened 2021-11-04 11:57 UTC by andrgit

2021-11-07 10:58 UTC, vasilikliapets commented on Andrei_hlebko/Lesson8_Extra/HW_8_Extra.py
> +
надо возвращать результат из wrapper, писал в телеге
тогда проверка будет проходить
x = func(2)
assert x is func(2)
sleep(4)
assert x is not func(2)

2021-11-07 11:05 UTC, vasilikliapets requested changes
поправь чуток

2021-11-09 10:10 UTC, andrgit commented
Bug fixed

2021-11-09 10:30 UTC, vasilikliapets approved these changes
ок

2021-11-09 10:30 UTC, merged