Homework8 extra pavel bohdan
vasilikliapets/QA03_onl pull request #123
Opened 2021-11-04 18:15 UTC by PavelBohdan

HW7 + HW8 + HW8_extra

2021-11-09 10:49 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_8/decor_8.py
> +        return
return пустой можно не писать, функция по умолчанию вернет None

2021-11-09 11:12 UTC, vasilikliapets requested changes
нужны правки

2021-11-09 11:12 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_8/tms_8.py
> +    result = args
переменная result явно лишняя, лучше сразу
return args

2021-11-09 11:12 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_8/tms_8.py
> +    return
вычислил результат, но возвращаешь 
return пустой, зачем тогда что то вычислять?

2021-11-09 11:12 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_8/tms_8.py
> +discriminant(4, 8, 2)
лихо ты придумал мат функцию)

2021-11-09 11:12 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_8_extra/decor_8_extra.py
> +
тут надо возвращать value, чтобы assertы отработали верно
вот из чатика в телеге
def wrapper(x):
            nonlocal end_time
            nonlocal result
            start = time.time()
            a = abs(end_time - start)
            if a < timeout:
                print(f"Кэш: {result}")
            else:
                result = func(x)
                print(result)
                end_time = time.time()
но в конце не забывайте возвращать результат выше
return result

2021-11-10 15:30 UTC, PavelBohdan reviewed
Поправил

2021-11-10 15:30 UTC, PavelBohdan commented on Pavel_Bohdan/Lesson_8/tms_8.py
> +    return letters()
Согласен.. исправил:)

2021-11-10 15:30 UTC, PavelBohdan commented on Pavel_Bohdan/Lesson_8/tms_8.py
> +discriminant(4, 8, 2)
:)

2021-11-10 15:33 UTC, PavelBohdan commented
Поправил вроде бы..

2021-11-11 11:08 UTC, vasilikliapets approved these changes
ok

2021-11-11 11:08 UTC, merged