Homework7 Valya Anikeeva
vasilikliapets/QA03_onl pull request #126
Opened 2021-11-07 16:41 UTC by ValyaAnikeeva

2021-11-10 06:20 UTC, vasilikliapets commented on Valya_Anikeeva/Lesson7/task_7_1.py
> +
надо докинуть в програму 
if __name__=="__main__"
тк счас из основного модуля банк и счет запускаются  сразу, а предлагает выбрать опцию только потом

2021-11-10 06:24 UTC, vasilikliapets requested changes
нужны небольшие правки

2021-11-10 06:24 UTC, vasilikliapets commented on Valya_Anikeeva/Lesson7/task_7_1.py
> +        # print("Год " + str(i))
есои принты уже отработали - их можно убирать из пр

2021-11-10 06:24 UTC, vasilikliapets commented on Valya_Anikeeva/Lesson7/task_7_2.py
> +    text_out = ''
по условию дз
1)	Для всех функций должна быть документация и аннотация
надо докинуть описание как
"""
"""

2021-11-10 06:24 UTC, vasilikliapets commented on Valya_Anikeeva/Lesson7/task_7_3.py
> +        continue
continue тут по сути не надо, у тебя и так продолжить выполнение программы дальше

2021-11-11 17:06 UTC, ValyaAnikeeva commented
> нужны небольшие правки

поправила

2021-11-13 10:44 UTC, vasilikliapets approved these changes
хорошо

2021-11-13 10:44 UTC, merged