Homework10/Andry_Hlebko
vasilikliapets/QA03_onl pull request #132
Opened 2021-11-09 10:58 UTC by andrgit

Homework10
Andry_Hlebko
Garden Shop

2021-11-20 13:02 UTC, vasilikliapets commented on Andrei_hlebko/Lesson10/task_10_flower_shop.py
> +# print(bouquet_1.price_bouquet())          #или так  правильнее??
правильнее через обьект
bouquet_1.price_bouquet()

2021-11-20 13:04 UTC, vasilikliapets commented on Andrei_hlebko/Lesson10/task_10_flower_shop.py
> +        return self.bouquet[index]
счас если ввети индекс, которого нет - падает ошибка
    return self.bouquet[index]
IndexError: tuple index out of range
тут неплохо было бы прикрутить какой if или try   except

2021-11-20 13:07 UTC, vasilikliapets commented on Andrei_hlebko/Lesson10/task_10_flower_shop.py
> +                    print(i)
тут и далее для посиковых методов надо докинуть else - такого цветка в букете нет, если я ищу того, чего нет в букете

2021-11-20 13:10 UTC, vasilikliapets requested changes
хорошо, но нужны небольшие правки

2021-11-20 16:14 UTC, andrgit reviewed
Fix bugs in HM10

2021-11-21 13:58 UTC, vasilikliapets approved these changes
ок

2021-11-21 13:58 UTC, merged