Homework9 Pavel Bohdan
vasilikliapets/QA03_onl pull request #134
Opened 2021-11-11 13:27 UTC by PavelBohdan

2021-11-15 12:06 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +        if not 1 in a and not 2 in a and not 3 in a and not 4 in a and not 7 in a and not 8 in a and not 9 in a and not 0 in a:
очень странный if
если ты хочешь получить сравнение 
a
 и еще чего то, то можно исползовать а>=5 and a<=6, или какой то лист

2021-11-15 12:07 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +def get_good_student():
эти функции лучше перенести в класс School и уже оттуда вызывать
они по сути ничего не дедают, а просто возвращаю переменную, которую и  так можно вернуть из класса

2021-11-15 12:10 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +        procent = 0
эта переменная не используется
у тебя уже вверху есть значение по умолчанию

2021-11-15 12:11 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +        return print(f'Deposit amount will be {amount}')
обычно или принт, или ретурн

2021-11-15 12:12 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +
по условию домашки
Написать класс Bank, метод deposit принимает аргументы N и R, и возвращает сумму, которая будет на счету пользователя.
у тебя метод депозит ничего не возвращает
и pass тут тоже не нужен

2021-11-15 12:16 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +    global good_students, automat_students, student_list
глобал лучше не использовать, а тут и смысла в нем нет - ты когда функции get_...
перенесешь в класс необходимость в нем отпадет

2021-11-15 12:17 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_9/tms_9.py
> +        self.ISBN = ISBN
с больших букв обычные переменные не называют

2021-11-15 12:22 UTC, vasilikliapets requested changes
нужны правки

2021-11-17 13:52 UTC, PavelBohdan commented
Исправления внесены

2021-11-20 10:39 UTC, vasilikliapets approved these changes
хорошо

2021-11-20 10:39 UTC, merged