Homework 8: Kate Khadarkevich
vasilikliapets/QA03_onl pull request #146
Opened 2021-11-15 10:13 UTC by KateKhadarkevich

2021-11-15 13:01 UTC, vasilikliapets commented on Kate_Khadarkevich/Lesson 8/decorators.py
> +        return
тут надо возвращать результат, например
func(*args)
иначе в этой строчке смысла нет

2021-11-15 13:14 UTC, vasilikliapets requested changes
поправь чуток

2021-11-15 13:28 UTC, KateKhadarkevich commented on Kate_Khadarkevich/Lesson 8/decorators.py
> +        return
поправила

2021-11-20 10:18 UTC, vasilikliapets approved these changes
ok

2021-11-20 10:18 UTC, merged