Eugene Shurpach : Homework9
vasilikliapets/QA03_onl pull request #156
Opened 2021-11-18 19:34 UTC by eshurpach

Added HW9

2021-11-20 10:52 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +    pass
он здесь не нужен

2021-11-20 10:53 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +    pass
убирай. он здесь ничего не делает

2021-11-20 10:54 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +        if Book.booking is not True and Book.taking is not True:
is not True - это лучше проверять как is False

2021-11-20 11:00 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            return self
а зачем ты везде возвращаешь self?
это не надо, он уже и так в себе будет хранить все твои изменения с обьектом

2021-11-20 11:00 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Книга зарезервирована!")
тут надо вставить инфу по тому, какая книга была зарезервирована

2021-11-20 11:01 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Эта книга зарезервирована! Стоит почитать что-нибудь другое.")
надо добавить информацию какая книга зарезервирована

2021-11-20 11:02 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Книга взята!")
добавить инфу какая именно книга взята (например название книги выводить)

2021-11-20 11:02 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            return self
убирай return self

2021-11-20 11:03 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Книги нет в наличии!")
добавить инфу какой книги нет в наличии

2021-11-20 11:03 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +        print("Книга возвращена!")
добавить какую книгу вернули
И тут надо проверять брал ли пользователь эту книгу или нет, а то у тебя счас можно сделать что пользователь вообще не брал книгу, но зато может ее вернуть

2021-11-20 11:05 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +user.taking(a)  # Книги нет!
задача работает не совсем правильно
вот напрмер мой тестовый случай
b_1 = Book("Остров сокровищ", "Роберт Стивенсон", 154, 5042429921)
b_2 = Book("book2", "Роберт Стивенсон", 154, 5042429921)
# добавление книги в библиотеку
# print(a.name)

user_1 = User("Шурпач Евгений")
# print(user.name)
# print(Book.book_count)

user_2 = User("Иванов Ванятко")
user_1.booking(b_1)
user_2.taking(b_1)
user_2.booking(b_1)
user_2.returning(b_1)
user_1.taking(b_1)
user_1.returning(b_1)
user_2.taking(b_1)
юзер2 можешь вернуть книгу, хотя даже не брал ее
после возвращения книги юзером1, юзер2 все еще не может ее взять, это очень странно

2021-11-20 11:07 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +# print(user.name)
если принты не нужны - убирай их из пр

2021-11-20 11:07 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_2.py
> +    def __init__(self, N, R):
большими буквами не называют параметры

2021-11-20 11:09 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_2.py
> +    def deposit(Investment):
тут тоже не надо с большой буквы, надо тебе еще раз повторить пеп8

2021-11-20 11:10 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_3.py
> +    def add_student(Students):
не надо с большой буквы

2021-11-20 11:10 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_3.py
> +        pass
не нужен

2021-11-20 11:12 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_3.py
> +    def print_name():
если это не статик метод, то должен быть self как первый параметр

2021-11-20 11:16 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_3.py
> +    def stud_auto():
нужен self как параметр

2021-11-20 11:17 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_3.py
> +    def get_stud_of_group(b):
self нужно докинуть

2021-11-20 11:18 UTC, vasilikliapets commented on eugene_shurpach/Lesson9/homework9/task_9_3.py
> +    def get_name_and_group():
надо переименовать функцию, чтобы она показывала что находит, например 
get_stud_and_group_mark_5_6_only

2021-11-20 11:18 UTC, vasilikliapets requested changes
нужны правки

2021-11-21 11:43 UTC, eshurpach commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Книга зарезервирована!")
Этого нет в постановке задачи.

2021-11-21 11:43 UTC, eshurpach commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Книга взята!")
Нет в постановке задачи

2021-11-21 11:44 UTC, eshurpach commented on eugene_shurpach/Lesson9/homework9/task_9_1.py
> +            print("Книги нет в наличии!")
Нет в постановке задачи

2021-11-21 11:45 UTC, eshurpach commented on eugene_shurpach/Lesson9/homework9/task_9_2.py
> +    def __init__(self, N, R):
Такие требования в ДЗ. Если это не мешает работе моего кода, то не вижу препятствий называть большими буквами.
Если это некорректно, то нужно актуализировать ДЗ либо предупреждать, что в ДЗ есть провокации на "ошибки".
Исправлено

2021-11-21 14:03 UTC, vasilikliapets approved these changes
ок

2021-11-21 14:03 UTC, merged