Homework 8_extra: Kate_Khadarkevich
vasilikliapets/QA03_onl pull request #157
Opened 2021-11-20 10:21 UTC by KateKhadarkevich

2021-11-20 10:49 UTC, vasilikliapets commented on Kate_Khadarkevich/Lesson 8_extra/task 2, 3.py
> +one_list = ['4', '11', '5', '3', '77', '14']
очень странно сортировать строковые величины, а не инты

2021-11-20 10:49 UTC, vasilikliapets commented on Kate_Khadarkevich/Lesson 8_extra/task 2, 3.py
> +sorted_list = sorted(one_list, key=lambda x: int(x[0:]))
тут не правильно, нужна лямбда функция
sorted_list = lambda x: ....

2021-11-20 10:50 UTC, vasilikliapets requested changes
поправь одну функцию

2021-11-20 11:06 UTC, KateKhadarkevich commented on Kate_Khadarkevich/Lesson 8_extra/task 2, 3.py
> +sorted_list = sorted(one_list, key=lambda x: int(x[0:]))
переделала

2021-11-21 13:56 UTC, vasilikliapets approved these changes
хорошо

2021-11-21 13:56 UTC, merged