Homework11: Pavel Bohdan
vasilikliapets/QA03_onl pull request #167
Opened 2021-11-26 20:07 UTC by PavelBohdan

Homework11

2021-11-27 10:11 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_11/tms_11.py
> +pig_1.ged_age()
такого метода нет, это норм что ты добавил, я его закоментил у себя в пайчареме 
# pig_1.ged_age()
и запустил
но при этом я все равно получаю сообщение
Для этого класса такого метода не существует

2021-11-27 10:13 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_11/tms_11.py
> +        print(f'{self.__age} years')
геттеры обычно возвращают значение через return, а не печатают его

2021-11-27 10:14 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_11/tms_11.py
> +        print(f'{self.__age} years')
return вместо print

2021-11-27 10:16 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_11/tms_11.py
> +    def __init__(self, list_of_animals = []):
list_of_animals = [] - обычно не используют mutable значение как значение по умолчанию, тк это передача по ссылке и ты будешь изменять один и тот же лист, вместо этого делают 
list_of_animals = None
а в самом ините
if list_of_animals is None:
list_of_animals=[]

2021-11-27 10:16 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_11/tms_11.py
> +        print(f'{self.animals[index].__class__.__name__} {self.animals[index].name}')
опять же - метод get должен возвращать, а не печатать

2021-11-27 10:17 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_11/tms_11.py
> +        return
просто return не имеет смысла, питон тебе и так вернет None без отсутствия return

2021-11-27 10:19 UTC, vasilikliapets requested changes
нужны небольшие правки

2021-12-05 19:25 UTC, PavelBohdan commented
Пофиксил

2021-12-11 10:14 UTC, vasilikliapets approved these changes
хорошо

2021-12-11 10:15 UTC, merged