Homework_11/Andry_Hlebko
vasilikliapets/QA03_onl pull request #169
Opened 2021-11-28 10:55 UTC by andrgit

Homework_11/Andry_Hlebko

2021-12-04 10:50 UTC, vasilikliapets commented on Andrei_hlebko/Lesson11/task_11_1(Ferm).py
> +        self.__ages__ = ages
__ages__ - указывает что это волшебный метод, а у тебя надо просто private переменную, обычно для этого в питоне используют
_ages,
в очень редких случаях 
__ages
но не __ages__

2021-12-04 10:56 UTC, vasilikliapets commented on Andrei_hlebko/Lesson11/task_11_1(Ferm).py
> +        print("Чык чырык")
зачет)

2021-12-04 11:02 UTC, vasilikliapets requested changes
поправь переменную

2021-12-04 17:17 UTC, andrgit reviewed
Fixed

2021-12-04 17:17 UTC, andrgit commented on Andrei_hlebko/Lesson11/task_11_1(Ferm).py
> +        self.__ages__ = ages
Bug fixed

2021-12-08 22:36 UTC, andrgit commented
Done

2021-12-11 10:13 UTC, vasilikliapets approved these changes
ok

2021-12-11 10:13 UTC, merged