Homework22/Andry_Hlebko
vasilikliapets/QA03_onl pull request #194
Opened 2022-01-04 11:00 UTC by andrgit

Homework22/Andry_Hlebko

2022-01-16 13:45 UTC, vasilikliapets commented on Andrei_hlebko/Lesson22/HM22/hm22.py
> +
не нашел у тебя третьего пункта
c.	Для всех остальных элементов создать методы, которые находят их на странице и возвращают элемент

2022-01-16 13:47 UTC, vasilikliapets requested changes
нуэно еще дописать описание элементов по пункту 3

2022-01-19 13:02 UTC, andrgit commented
Bug fixed!)

2022-01-22 09:48 UTC, vasilikliapets approved these changes
reviewed)

2022-01-22 09:48 UTC, merged