Homework8/anastasiya odintsova
vasilikliapets/QA03_onl pull request #205
Opened 2022-01-07 20:18 UTC by AnastasiyaOdintsova

2022-01-07 20:19 UTC, AnastasiyaOdintsova commented
my homework)

2022-01-10 11:21 UTC, AnastasiyaOdintsova commented
На предыдущий коммит можно не смотреть

2022-01-10 12:43 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 6/HomeWork_6.py
> +count_text(a)
после вывоза функции и вода yty - на экране не отображается количество букв
есть подозрение что в любом случае количество букв не выводит

2022-01-10 12:46 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 6/HomeWork_6.py
> +changed_list_2 = change_list(my_list)
используешь my_list как аргумент, но не определяешь его до этого

2022-01-10 12:52 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 7/HomeWork_7_3.py
> +        bank(a, years)
переменные a и years не определены
NameError: name 'a' is not defined

2022-01-10 12:53 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 7/HomeWork_7_3.py
> +        enode()
encode instead of enode

2022-01-10 12:59 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 8/HomeWork_8.py
> +    return
тут надо return wrapper

2022-01-10 13:01 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 8/HomeWork_8.py
> +def decorator_7(n):
тк это просто функция, но лучше не называть ее decorator, очень путает

2022-01-10 13:02 UTC, vasilikliapets commented on Anastasiya_Odintsova/Lesson 8/HomeWork_8.py
> +def decorator_8(x, y):
такая же история с именованием, сам декоратор ты назвала func_1, а саму функцию decorator_8, нужно изменить названия

2022-01-10 13:02 UTC, vasilikliapets requested changes
нужны исправления

2022-01-11 07:14 UTC, AnastasiyaOdintsova commented
Исправления

2022-01-11 12:04 UTC, vasilikliapets approved these changes
хорошо

2022-01-11 12:04 UTC, merged