Pavel Bohdan: Homework21
vasilikliapets/QA03_onl pull request #209
Opened 2022-01-08 13:50 UTC by PavelBohdan

2022-01-14 12:17 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_21/test_HW_21.py
> +def test_smith(browser, login, password):
падает тест ('sam', 'password')
E       assert 'You logged into a secure area!' in 'Your username is invalid!\n×'
E        +  where 'Your username is invalid!\n×' = <selenium.webdriver.remote.webelement.WebElement (session="36f3400b4065ac4feb21a0612adbe70d", element="982bf566-1294-425b-9ac3-7cb25d4f5759")>.text

student.py:22: AssertionError

2022-01-14 12:24 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_21/test_HW_21.py
> +    browser.get('http://the-internet.herokuapp.com/')
эту запись ты используешь в трех тестах, сделай доп фикстуру, которая возвращает 
return browser.get('http://the-internet.herokuapp.com/')
а принимает  фикстуру browser()
и потом используй эту новую фикстуру в тестах своих

2022-01-14 12:24 UTC, vasilikliapets requested changes
нужны доработки

2022-01-22 14:28 UTC, PavelBohdan commented on Pavel_Bohdan/Lesson_21/test_HW_21.py
> +def test_smith(browser, login, password):
Тогда у меня вопрос, как мне разделить ассерты для параметризованного теста? Или надо делать без параметризации?

2022-01-24 08:00 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_21/test_HW_21.py
> +def test_smith(browser, login, password):
как вариант - два теста, параметизацию ты используешь если данные разные, а поведение теста одинаковое, если поведение разное - то это уже получается два разных теста

2022-01-26 13:48 UTC, PavelBohdan commented
Пофиксил. Добавил в параметризацию XFail

2022-01-26 13:55 UTC, vasilikliapets approved these changes
ок

2022-01-26 13:55 UTC, merged