Pavel Bohdan: Homework22
vasilikliapets/QA03_onl pull request #210
Opened 2022-01-08 13:51 UTC by PavelBohdan

2022-01-16 13:39 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_22/test_HW_22_Locators.py
> +            By.CSS_SELECTOR, "div.inventory_item:nth-child(2) > div:nth-child(2) > div:nth-child(2) > div:nth-child(1)").text
выглядит дико сложным, как нить проще пробовал найти?

2022-01-16 13:42 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_22/test_HW_22_Locators.py
> +        onesie_price = browser.find_element(
по задания
a.	Вывести информацию по всем товарам, которая возвращает их название и цену
это значит Принт сделать, у тебя ничего не выводится счас

2022-01-16 13:42 UTC, vasilikliapets requested changes
нужно немного поправить

2022-01-27 13:06 UTC, PavelBohdan commented
Немного)) поправил

2022-01-27 13:16 UTC, vasilikliapets approved these changes
ок

2022-01-27 13:16 UTC, merged