Pavel Bohdan: Homework23
vasilikliapets/QA03_onl pull request #211
Opened 2022-01-08 13:51 UTC by PavelBohdan

2022-01-22 10:56 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_23/test_HW_23.py
> +    browser.get('https://ultimateqa.com/filling-out-forms/')
у тебя открывается одна и та же страница в каждом тесте, вынеси это действие в фикстуру

2022-01-22 10:57 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_23/test_HW_23.py
> +    button.click()
это не тест, а функция, тест должен что то проверять (делать ассерт) 
а ты тут просто производишь какие то действия, кстати в задании это тоже не идет как тест, а просто как действия
можно или добавить какой ассерт, или просто сделать это функцией или фикстурой

2022-01-22 10:58 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_23/test_HW_23.py
> +    submith_button.click()
где ассерт?))

2022-01-22 10:58 UTC, vasilikliapets requested changes
посмотри коменты и доработай

2022-01-27 13:43 UTC, PavelBohdan commented
Доработал

2022-01-29 13:16 UTC, vasilikliapets approved these changes
хорошо

2022-01-29 13:18 UTC, merged