Eugene Shurpach: Homework23
vasilikliapets/QA03_onl pull request #222
Opened 2022-01-16 11:06 UTC by eshurpach

Added homework23

2022-01-22 11:02 UTC, vasilikliapets commented on eugene_shurpach/Lesson23/homework23/test.py
> +def test_1(page_driver):
обычно тесты именуют по тому, что они делают
просто test_1 - не очень смотрится

2022-01-22 11:05 UTC, vasilikliapets commented on eugene_shurpach/Lesson23/homework23/test.py
> +    assert ('Make sure you fill in all required fields.') in check_message.text
первый тест должен проверять успешность заполнения, а не ошибку
1.	Заполните поле Name and Message
2.	Нажмите на кнопку "Submit"
3.	Проверьте наличие сообщения "Form filled out successfully"

2022-01-22 11:05 UTC, vasilikliapets requested changes
нужны доработки

2022-01-22 13:26 UTC, eshurpach commented on eugene_shurpach/Lesson23/homework23/test.py
> +def test_1(page_driver):
![2022-01-22_16-25-56](https://user-images.githubusercontent.com/91487761/150640302-c29e3920-792f-429e-ad77-54c7acb6d84c.png)
Так тесты названы в задании ¯\_(ツ)_/¯

2022-01-22 13:27 UTC, eshurpach commented on eugene_shurpach/Lesson23/homework23/test.py
> +    assert ('Make sure you fill in all required fields.') in check_message.text
В чате было обсуждение, что кнопка Submit не нажимается из автотеста и указание ловить то сообщение, которое появляется. 
Исправил, но так тест падает (по крайней мере у меня)

2022-01-24 07:58 UTC, vasilikliapets approved these changes
хорошо

2022-01-24 07:58 UTC, merged