Homework27 Pavel Bohdan
vasilikliapets/QA03_onl pull request #230
Opened 2022-01-21 14:15 UTC by PavelBohdan

2022-01-29 13:37 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_27/HW_27.py
> +                   passwd="********",
ну тут большого секрета нет) я все равно на твою мащину не зайду)

2022-01-29 13:38 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_27/HW_27.py
> +# query = "SELECT * FROM orders WHERE salesman_id=2"
тут надо не все столбцы, а только три ( у тебя в таблице 4 столбца)

2022-01-29 13:40 UTC, vasilikliapets commented on Pavel_Bohdan/Lesson_27/HW_27.py
> +# query = "SELECT * FROM orders WHERE ord_no BETWEEN 1 and 7"
а зачем ты преобразовал изначально 70001 в 1 и тд?)

2022-01-29 13:40 UTC, vasilikliapets requested changes
посмотри коменты

2022-01-29 14:53 UTC, PavelBohdan commented on Pavel_Bohdan/Lesson_27/HW_27.py
> +                   passwd="********",
у меня просто всего пару паролей для доступа ко всему и тут один из них))

2022-01-29 14:55 UTC, PavelBohdan commented on Pavel_Bohdan/Lesson_27/HW_27.py
> +# query = "SELECT * FROM orders WHERE ord_no BETWEEN 1 and 7"
честно думал, чтобы все порядковые позиции были в одном стиле, для удобного поиска в будущем.. ну как-то так))

2022-02-01 14:41 UTC, vasilikliapets approved these changes
ok

2022-02-01 14:41 UTC, merged