Homework26/Andry_Hlebko(Page_obj)
vasilikliapets/QA03_onl pull request #231
Opened 2022-01-21 22:20 UTC by andrgit

Homework26/Andry_Hlebko

2022-01-22 13:37 UTC, vasilikliapets commented on Andrei_hlebko/Lesson26/hm26_page_obj/test_main_page.py
> +    assert login_page.get_oops(), "Oops message doesn't exist"
странный assert
обычно ты возвращаемое значение сравниваешь с чем то, а у тебя всегда будет Тру тк питон приведет твое возвращамое значение к True если только оно будет не пустое

2022-01-22 13:37 UTC, vasilikliapets commented on Andrei_hlebko/Lesson26/hm26_page_obj/test_main_page.py
> +    login_page.get_oops(), "Opps message doesn't exist"
тут вообще ассерат нет
надо добавить

2022-01-22 13:37 UTC, vasilikliapets requested changes
поправь немного

2022-01-23 20:28 UTC, andrgit reviewed
Bug Fixed

2022-01-24 08:21 UTC, vasilikliapets approved these changes
хорошо

2022-01-24 08:21 UTC, merged