Homework3: Valya Anikeeva
vasilikliapets/QA03_onl pull request #37
Opened 2021-10-04 19:32 UTC by ValyaAnikeeva

2021-10-05 13:25 UTC, vasilikliapets commented on Valya_Anikeeva/Lesson3/task_3.py
> +print("Task10: {r}, {f} Task11: {y}, {h}". format(r=r,f=f,y=y,h=h))
переменные лучше называть осмыыленно, а то очень легко будет запутаться потом

2021-10-05 13:27 UTC, vasilikliapets requested changes
вижу что делала реверт, норм прошло?

2021-10-07 05:39 UTC, ValyaAnikeeva commented on Valya_Anikeeva/Lesson3/task_3.py
> +a,b = 10,23
a,b = b, -a
Так и сделала, может не заметили

2021-10-07 07:03 UTC, vasilikliapets commented on Valya_Anikeeva/Lesson3/task_3.py
> +a,b = 10,23
ага, старею)

2021-10-07 07:04 UTC, vasilikliapets approved these changes
хорошо, мержим

2021-10-07 07:04 UTC, merged