Homework5/Andry_Hlebko
vasilikliapets/QA03_onl pull request #56
Opened 2021-10-11 15:01 UTC by andrgit

2021-10-16 12:55 UTC, vasilikliapets commented on Andrei_hlebko/Lesson4/task_4_4.py
> +del spis_10[6]
не вставил на 3-ю позицию

2021-10-16 12:57 UTC, vasilikliapets commented on Andrei_hlebko/Lesson4/task_4_5.py
> +print(sorted(slovar_a.items(), reverse=True))#5
здесь на выходе будет лист тюплов, а надо дикт

2021-10-16 13:04 UTC, vasilikliapets commented on Andrei_hlebko/Lesson4/task_4_6.py
> +list_uniq = tuple(list_uniq)#4
плозая правтика именовать переменную list_ но записывать туда set,

2021-10-16 13:08 UTC, vasilikliapets commented on Andrei_hlebko/Lesson5/5.1(v2).py
> +    elif bull+cow == 4:
сравнивать надо быков  иизаканчивать программу когда быков станет 4,
а у тебя 2 быка и 2 коровы - игра закончена

2021-10-16 13:13 UTC, vasilikliapets commented on Andrei_hlebko/Lesson5/task_5_1(bulls_and_cows).py
> +        return print((f"Вы выиграли! Загаданное число было: {comp_chislo}. Количество быков: {bull}! Поздравляем!"))
вторая версия работает лучше, но надо убрать из вывода число, загаданное компьютером

2021-10-16 13:18 UTC, vasilikliapets commented on Andrei_hlebko/Lesson5/task_5_5(same_elem).py
> +for i in prim4:#Проходимся циклом по каждому значению в списке и записываем в i
можно легче через set, но работает и так

2021-10-16 13:20 UTC, vasilikliapets requested changes
поправь замечания
в след раз лучше не обьединять две домашки в одну, я путаюсь)

2021-10-17 12:06 UTC, andrgit commented on Andrei_hlebko/Lesson4/task_4_5.py
> +print(sorted(slovar_a.items(), reverse=True))#5
task 4_5 bug fixed

2021-10-17 12:09 UTC, andrgit commented on Andrei_hlebko/Lesson4/task_4_6.py
> +list_uniq = {*list_a}#2
а что-то забыл что так можно))) Я думал что фордом можно, но конечно set быстрее)

2021-10-17 12:12 UTC, andrgit commented on Andrei_hlebko/Lesson4/task_4_6.py
> +list_uniq = tuple(list_uniq)#4
принято, исправлюсь) по очереди делал задания, и не обратил внимание на имя переменной.

2021-10-17 12:13 UTC, andrgit commented on Andrei_hlebko/Lesson5/5.1(v2).py
> +    elif bull+cow == 4:
Я жизнь и голову сломал себе с этими быками и коровами)))
Лучше тогда со второй версией буду работать)))

2021-10-17 12:14 UTC, andrgit commented on Andrei_hlebko/Lesson5/task_5_1(bulls_and_cows).py
> +        return print((f"Вы выиграли! Загаданное число было: {comp_chislo}. Количество быков: {bull}! Поздравляем!"))
task 5_1 bug fixed

2021-10-17 12:32 UTC, andrgit commented on Andrei_hlebko/Lesson5/task_5_5(same_elem).py
> +for i in prim4:#Проходимся циклом по каждому значению в списке и записываем в i
а как можно сделать через set? оно же в сет просто скидывает неповторяющиеся элементы. Или как-то сравнивать len этого значения раньше?Потому что если просто делать set(prim2) он все время пишет True

2021-10-17 12:40 UTC, andrgit commented on Andrei_hlebko/Lesson5/task_5_7.py
> +    x += i
А есть какая-то принципиальная разница когда использовать sum просто, а когда проходится по элементам в цикле? Нагруженность памяти, или еще какая штука?
 Task 5_7 add second solution

2021-10-17 18:52 UTC, closed without merging