Homework 7 Hanna Dziahel
vasilikliapets/QA03_onl pull request #90
Opened 2021-10-24 22:14 UTC by hanna-dziahel

2021-10-30 12:50 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson7/task7_3.py
> +# Общий модуль, который предоставляет возможность выбрать одну из двух
программа корректно не передает мой выбор
Выберите программу:
            1) Банковский вклад
            2) Шифр Цезаря
            3) Выход из программы
Введите номер пункта меню: 1
Введен неверный номер пункта меню

2021-10-30 12:52 UTC, vasilikliapets commented on Hanna_Dziahel/Lesson7/task7_2.py
> +        print(encode(user_phrase, user_offset))
программа не шифрует
Выберите операцию:
    1) Encode
    2) Decode
Выбранная операция: 1
Введите фразу: My
Введите число-сдвиг для шифра: 2
Traceback (most recent call last):
  File "/Users/v_kliapets/PycharmProjects/techme_skills/tms_7/student.py", line 68, in <module>
    run_choosing_process()
  File "/Users/v_kliapets/PycharmProjects/techme_skills/tms_7/student.py", line 45, in run_choosing_process
    choose_program(random_value)
  File "/Users/v_kliapets/PycharmProjects/techme_skills/tms_7/student.py", line 65, in choose_program
    shifr.run_ceasar()
  File "/Users/v_kliapets/PycharmProjects/techme_skills/tms_7/shifr.py", line 129, in run_ceasar
    print(encode(user_phrase, user_offset))
  File "/Users/v_kliapets/PycharmProjects/techme_skills/tms_7/shifr.py", line 38, in encode
    element_index = alphabet.index(element)
ValueError: substring not found

Process finished with exit code 1

2021-10-30 12:52 UTC, vasilikliapets requested changes
нужны доработки

2021-11-02 11:03 UTC, hanna-dziahel commented on Hanna_Dziahel/Lesson7/task7_2.py
> +        print(encode(user_phrase, user_offset))
Added changes

2021-11-02 11:03 UTC, hanna-dziahel commented on Hanna_Dziahel/Lesson7/task7_3.py
> +# Общий модуль, который предоставляет возможность выбрать одну из двух
Added changes

2021-11-03 09:25 UTC, vasilikliapets approved these changes
хорошо

2021-11-03 09:25 UTC, merged