Homework 7: Darya Tyupa
vasilikliapets/QA03_onl pull request #91
Opened 2021-10-25 13:55 UTC by DaryaTyupa

свой шифровальщик не придумала, взяла азбуку морзе.

2021-10-30 13:04 UTC, vasilikliapets commented on Darya_Tyupa/Lesson7/shifr_cezar.py
> +init_alph = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u',
чтобы это не писать руками, есть константа уже
string.ascii_lowercase
Out[123]: 'abcdefghijklmnopqrstuvwxyz'
ее потом сплитишь и получаешь готовый список с буквами

2021-10-30 13:06 UTC, vasilikliapets commented on Darya_Tyupa/Lesson7/morze_decoder.py
> +            result += morze_dict.get(list(alphabet_dict.keys())[list(alphabet_dict.values()).index(i)])
это лучше разбить на несколько операций, а то очень непонятно что вообще здесь происходит)

2021-10-30 13:07 UTC, vasilikliapets commented on Darya_Tyupa/Lesson7/main_HomeWork_7.py
> +    global count
тут без global не обойтись? 
очень это стремная вещь - использовать глобал

2021-10-30 13:08 UTC, vasilikliapets requested changes
нужны небольшие правки

2021-10-30 15:25 UTC, DaryaTyupa commented on Darya_Tyupa/Lesson7/shifr_cezar.py
> +init_alph = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u',
done

2021-10-30 15:25 UTC, DaryaTyupa commented on Darya_Tyupa/Lesson7/morze_decoder.py
> +            result += morze_dict.get(list(alphabet_dict.keys())[list(alphabet_dict.values()).index(i)])
разбила)

2021-11-03 11:49 UTC, vasilikliapets approved these changes
хорошо

2021-11-03 11:49 UTC, merged